name: QuietAnimals
version: ${project.version}
main: me.peridactite.quietanimals.QuietAnimals
api-version: 1.13
authors: [Peridactite]
description: Get those animals to shut up
commands:
  hushAnimals:
    description: Quiet Animals
    usage: /hushAnimals <True/False> <range> #this is just what user sees when they type the command args wrong